name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # root 
            sudo su

            # Navigate to the repo directory
            cd /var/www/repos/website
            
            # Pull the latest code from GitHub
            git pull origin main
            
            # Sync the repo files to the Nginx directory
            rsync -av --delete /var/www/repos/website/ /var/www/html/website/
            
            # Restart Nginx to apply changes
            sudo systemctl restart nginx
            
            echo "Deployment completed at $(date)"
