name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /var/www/repos/website || exit 1
            sudo git reset --hard origin/main
            sudo git pull origin main
            
            sudo cp -r /var/www/repos/website/ /var/www/html/website/
                        
            sudo systemctl restart nginx